# ----- START Secret Scanning -----
name: Devguard Secret Scanning Workflow
on:
    push:

jobs:
    secret-scanning:
        uses: l3montree-dev/devguard-action/.github/workflows/secret-scanning.yml@main
# ----- END Secret Scanning -----
