# DevSecOps Workflow Definition
# This workflow is triggered on every push to the repository
name: DevSecOps Workflow
on:
    push:

jobs:
  # ----- BEGIN Secret Scanning Job -----
    uses: l3montree-dev/devguard-action/.github/workflows/secret-scanning.yml@main
    with:
      asset-name: "psyslop/projects/psyslop/assets/psyslop"
      api-url: https://api.main.devguard.org
    secrets:
      devguard-token: "${{ secrets.DEVGUARD_TOKEN }}"

  # ----- END Secret Scanning Job -----
