# ----- START Container Scanning -----
name: Devguard Container Scanning Workflow
on:
    push:

jobs:
    container-scanning:
        uses: l3montree-dev/devguard-action/.github/workflows/secret-scanning.yml@main
        with:
            asset-name: psyslop/projects/psyslop/assets/psyslop
        secrets:
            devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
# ----- END Container Scanning -----
